import type { LucideIcon } from "lucide-react";
import { Banknote, CreditCard, Landmark, Smartphone, Wallet } from "lucide-react";

export type LookupOption = { id?: number; code: string; name: string };

/** Shared payment UI — same modal for members and applicants. */
export type PaymentAudience = "member" | "applicant";

export type FeePurpose =
  | "joining"
  | "annual"
  | "accommodation"
  | "corkage"
  | "other";

/** Dues snapshot from GET /api/applications/{id}/dues */
export type ApplicationDues = {
  membershipTypeId?: number | null;
  membershipTypeName?: string | null;
  joiningFeeTypeId: number;
  annualFeeTypeId: number;
  joiningFee: number;
  annualSubscription: number;
  joiningPaid: number;
  annualPaid: number;
  joiningBalance: number;
  annualBalance: number;
  totalDue: number;
  totalPaid: number;
  balance: number;
  halfYearAnnual: boolean;
  joiningInvoiced?: boolean;
  annualInvoiced?: boolean;
};

export type MemberSubscription = {
  standing: string;
  detail: string;
  paysSubscription: boolean;
  year: number;
  amountDue: number;
  amountPaid: number;
  outstanding: number;
  broughtForward?: number;
  dueDate: string;
  postingDeadline: string;
  removalDeadline: string;
  discountPercent: number;
  joiningFeeDue: number;
  joiningPaid: number;
  joiningOutstanding: number;
  entranceFeeWaived: boolean;
  balance: number;
  membershipNo?: string | null;
  membershipTypeCode?: string | null;
  membershipTypeName?: string | null;
  fullAnnualRate?: number;
  isLifeExempt?: boolean;
  isSeniorMember?: boolean;
  halfYearProrated?: boolean;
  canVote?: boolean;
  votingBlockedByArrears?: boolean;
  clubCreditBalance?: number;
  /** Unallocated advance receipts plus club-card credit. */
  availableCredit?: number;
  continuousMembershipYears?: number;
  ageYears?: number | null;
  statusCode?: string;
  isActive?: boolean;
  /** Future year already generated by Finance renewal (demo / early renew). */
  upcomingYear?: number | null;
  upcomingAmountDue?: number;
  upcomingAmountPaid?: number;
  upcomingOutstanding?: number;
  upcomingPaymentStatus?: string;
  annualPaymentStatus?: string;
  joiningPaymentStatus?: string;
  openCharges?: MemberOpenCharge[];
};

export type MemberOpenCharge = {
  kind: string;
  id: number;
  description: string;
  amount: number;
  feeTypeCode: string;
};

export type PaymentHistoryRow = {
  transactionId: number;
  receiptNumber?: string | null;
  method?: string | null;
  status?: string | null;
  statusCode?: string | null;
  amount: number;
  paymentDate?: string | null;
  mpesaCode?: string | null;
  chequeNo?: string | null;
  chequeBankName?: string | null;
  chequeBankCode?: string | null;
  chequeDate?: string | null;
  chequeFileName?: string | null;
  chequeFileUrl?: string | null;
  feeType?: string | null;
  referenceNote?: string | null;
};

export type MemberPayPayload = {
  paymentMethodId: number;
  feeTypeCode: string;
  amount: number;
  paymentDate: string;
  mpesaCode?: string | undefined;
  mpesaPhone?: string | undefined;
  chequeNo?: string | undefined;
  chequeBankName?: string | undefined;
  chequeBankCode?: string | undefined;
  chequeDate?: string | undefined;
  chequeFileName?: string | undefined;
  chequeFileUrl?: string | undefined;
  referenceNote?: string | undefined;
  paymentStatusCode?: string | undefined;
  lineDescription?: string | undefined;
  subscriptionYear?: number | undefined;
};

export type MpesaStkResult = {
  checkoutRequestId: string;
  merchantRequestId: string;
  customerMessage: string;
  status: string;
  phone: string;
  amount: number;
};

export const FEE_PURPOSE_LABEL: Record<FeePurpose, string> = {
  joining: "Joining",
  annual: "Annual subscription",
  accommodation: "Accommodation",
  corkage: "Corkage ",
  other: "Custom club charge",
};

export const FEE_PURPOSE_CODE: Record<FeePurpose, string> = {
  joining: "JOINING",
  annual: "ANNUAL",
  accommodation: "ACCOMMODATION",
  corkage: "CORKAGE",
  other: "OTHER",
};

export const METHOD_ICONS: Record<string, LucideIcon> = {
  CASH: Wallet,
  MPESA: Smartphone,
  CHEQUE: Landmark,
  BANK_TRANSFER: Landmark,
  CARD: CreditCard,
  CREDIT: CreditCard,
  CREDIT_CARD: CreditCard,
  CLUB_CARD: Banknote,
  ACCOUNT_BALANCE: Banknote,
  CLUB_CREDIT: Banknote,
};

export const CHEQUE_BANKS = [
  "KCB Bank Kenya",
  "Absa Bank Kenya",
  "Equity Bank Kenya",
  "Co-operative Bank of Kenya",
  "NCBA Bank Kenya",
  "Stanbic Bank Kenya",
  "I&M Bank Kenya",
  "Diamond Trust Bank Kenya",
  "Family Bank Kenya",
];

export const PREFERRED_METHODS = [
  "MPESA",
  "CARD",
  "CHEQUE",
  "CLUB_CARD",
  "BANK_TRANSFER",
  "CASH",
];

export function normalizeMethodCode(code?: string | null) {
  return (code ?? "").trim().toUpperCase().replace(/[-\s]/g, "_");
}

export function isPaidStatus(status?: string | null) {
  const s = (status ?? "").toLowerCase().replace(/[-\s]/g, "_");
  return (
    s === "paid"
    || s === "waived"
    || s === "partially_paid"
    || s === "partiallypaid"
    || s === "settled"
    || s === "refunded"
    || s === "reversed"
  );
}

export function paymentStatusTone(status?: string | null, statusCode?: string | null) {
  const code = (statusCode ?? status ?? "").trim().toUpperCase().replace(/[-\s]/g, "_");
  if (code === "PAID" || code === "WAIVED" || code === "SETTLED" || code === "PAIDSTATUS") {
    return "ok" as const;
  }
  if (code === "PARTIALLY_PAID" || code === "PARTIALLYPAY" || code === "PARTIALLYPAID") {
    return "partial" as const;
  }
  if (code === "REFUNDED") return "refunded" as const;
  if (code === "REVERSED") return "reversed" as const;
  if (code === "VOIDED" || code === "CANCELLED" || code === "CANCELED" || code === "REJECTED") {
    return "voided" as const;
  }
  return "pending" as const;
}

export function liveFeeStatusLabel(code?: string | null) {
  switch ((code ?? "").trim()) {
    case "Paid":
      return "Paid";
    case "PartiallyPaid":
      return "Partially paid";
    case "PendingVerification":
      return "Pending verification";
    case "Waived":
      return "Waived";
    case "NotBilled":
      return "Awaiting invoice";
    case "Refunded":
      return "Refunded";
    case "Reversed":
      return "Reversed";
    default:
      return "Unpaid";
  }
}

export function isReceiptViewable(status?: string | null, statusCode?: string | null) {
  const s = (statusCode ?? status ?? "").trim().toUpperCase().replace(/[-\s]/g, "_");
  return s === "PAID" || s === "WAIVED" || s === "PARTIALLY_PAID" || s === "SETTLED" || s === "REFUNDED";
}

export function isVoidablePayment(row: Pick<PaymentHistoryRow, "status" | "statusCode" | "receiptNumber">) {
  if (row.receiptNumber) return false;
  const code = (row.statusCode ?? row.status ?? "").trim().toUpperCase().replace(/[-\s]/g, "_");
  return code === "PENDING" || code === "INITIATED" || code === "UNCLEARED";
}

export function isVoidedStatus(status?: string | null, statusCode?: string | null) {
  const code = (statusCode ?? status ?? "").trim().toUpperCase().replace(/[-\s]/g, "_");
  return code === "VOIDED" || code === "CANCELLED" || code === "CANCELED" || code === "REJECTED";
}

export function sortPaymentMethods(rows: LookupOption[]) {
  return [...rows].sort((a, b) => {
    const ai = PREFERRED_METHODS.indexOf(normalizeMethodCode(a.code));
    const bi = PREFERRED_METHODS.indexOf(normalizeMethodCode(b.code));
    return (ai === -1 ? 99 : ai) - (bi === -1 ? 99 : bi);
  });
}

export function standingLabel(code?: string | null) {
  return (code ?? "InGoodStanding").replace(/([a-z])([A-Z])/g, "$1 $2").trim();
}

/** Map application fee schedule dues into the shared payment form model. Uninvoiced fees stay hidden. */
export function applicationDuesToSubscription(dues: ApplicationDues): MemberSubscription {
  const year = new Date().getFullYear();
  const joiningInvoiced = Boolean(dues.joiningInvoiced);
  const annualInvoiced = Boolean(dues.annualInvoiced);
  const joiningFee = joiningInvoiced ? Number(dues.joiningFee || 0) : 0;
  const joiningPaid = joiningInvoiced ? Number(dues.joiningPaid || 0) : 0;
  const joiningOutstanding = joiningInvoiced ? Number(dues.joiningBalance || 0) : 0;
  const annualDue = annualInvoiced ? Number(dues.annualSubscription || 0) : 0;
  const annualPaid = annualInvoiced ? Number(dues.annualPaid || 0) : 0;
  const annualOutstanding = annualInvoiced ? Number(dues.annualBalance || 0) : 0;
  const balance = joiningOutstanding + annualOutstanding;
  return {
    standing: balance <= 0 ? "InGoodStanding" : "PendingPayment",
    detail: dues.halfYearAnnual
      ? "Application fees — annual subscription pro-rated to 31 Dec"
      : "Application joining and first-year subscription fees",
    paysSubscription: annualInvoiced,
    year,
    amountDue: annualDue,
    amountPaid: annualPaid,
    outstanding: annualOutstanding,
    dueDate: "",
    postingDeadline: "",
    removalDeadline: "",
    discountPercent: 0,
    joiningFeeDue: joiningFee,
    joiningPaid,
    joiningOutstanding,
    joiningPaymentStatus: joiningInvoiced ? undefined : "NotBilled",
    annualPaymentStatus: annualInvoiced ? undefined : "NotBilled",
    entranceFeeWaived: joiningInvoiced && joiningFee <= 0,
    balance,
    membershipTypeName: dues.membershipTypeName ?? null,
    halfYearProrated: Boolean(dues.halfYearAnnual),
    clubCreditBalance: 0,
    openCharges: [],
  };
}

function roundMoney(value: number) {
  return Math.round((Number(value) || 0) * 100) / 100;
}

/** Unallocated advance receipts the statement has already taken off the running balance. */
export function memberAvailableCredit(
  sub: Pick<MemberSubscription, "availableCredit" | "clubCreditBalance">,
) {
  return Math.max(0, roundMoney(Number(sub.availableCredit ?? sub.clubCreditBalance ?? 0)));
}

export type MemberAccountPosition = {
  /** Full unallocated credit before it is set against open dues. */
  credit: number;
  /** Portion already used to reduce what the member still owes. */
  creditApplied: number;
  /** What is still available after open dues. Zero once the advance has been used up. */
  creditRemaining: number;
  joiningNet: number;
  broughtForwardNet: number;
  currentYearNet: number;
  /** Current year plus brought forward, after credit. This is what annual payment should collect. */
  subscriptionNet: number;
  upcomingNet: number;
  /** Same net as the statement closing balance: invoiced dues minus advance credit. */
  balanceNet: number;
};

/**
 * Outstanding and advance credit are already net of payment allocations.
 * Do not subtract credit from the balance again.
 */
export function memberAccountPosition(sub: MemberSubscription): MemberAccountPosition {
  const credit = memberAvailableCredit(sub);
  const broughtForwardNet = Math.max(0, roundMoney(Number(sub.broughtForward || 0)));
  const currentYearNet = Math.max(0, roundMoney(roundMoney(sub.outstanding) - broughtForwardNet));
  const joiningNet = Math.max(0, roundMoney(sub.joiningOutstanding));
  const upcomingNet = Math.max(0, roundMoney(Number(sub.upcomingOutstanding || 0)));
  const balanceNet = Math.max(0, roundMoney(Number(sub.balance || 0)));
  return {
    credit,
    creditApplied: 0,
    creditRemaining: credit,
    joiningNet,
    broughtForwardNet,
    currentYearNet,
    subscriptionNet: roundMoney(currentYearNet + broughtForwardNet),
    upcomingNet,
    balanceNet,
  };
}

export const APPLICANT_FEE_PURPOSES: FeePurpose[] = ["joining", "annual"];
export const MEMBER_FEE_PURPOSES: FeePurpose[] = [
  "joining",
  "annual",
  "accommodation",
  "corkage",
  "other",
];
