/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccommodationRouteImport } from './routes/accommodation'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ApplicationRouteImport } from './routes/application'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as CommitteeBallotRouteImport } from './routes/committee-ballot'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as ElectionRouteImport } from './routes/election'
import { Route as EndorsementsRouteImport } from './routes/endorsements'
import { Route as ExistingMembersRouteImport } from './routes/existing-members'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as GovernanceRouteImport } from './routes/governance'
import { Route as GuestsRouteImport } from './routes/guests'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ManageCommitteeRouteImport } from './routes/manage-committee'
import { Route as MembersRouteImport } from './routes/members'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ReceptionRouteImport } from './routes/reception'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RegisterMemberRouteImport } from './routes/register-member'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SupportRouteImport } from './routes/support'
import { Route as UserManagementRouteImport } from './routes/user-management'
import { Route as CommitteeBallotIndexRouteImport } from './routes/committee-ballot.index'
import { Route as CommitteeBallotAttendanceRouteImport } from './routes/committee-ballot.attendance'
import { Route as CommitteeBallotCandidatesRouteImport } from './routes/committee-ballot.candidates'
import { Route as CommitteeBallotPendingRouteImport } from './routes/committee-ballot.pending'
import { Route as ExistingMembersIndexRouteImport } from './routes/existing-members.index'
import { Route as ExistingMembersAccountIdRouteImport } from './routes/existing-members.$accountId'
import { Route as ManageCommitteeIndexRouteImport } from './routes/manage-committee.index'
import { Route as ManageCommitteeCurrentTermRouteImport } from './routes/manage-committee.current-term'
import { Route as ManageCommitteeMeetingsRouteImport } from './routes/manage-committee.meetings'
import { Route as ManageCommitteeMembersRouteImport } from './routes/manage-committee.members'
import { Route as ManageCommitteeNewTermRouteImport } from './routes/manage-committee.new-term'
import { Route as MembersIndexRouteImport } from './routes/members.index'
import { Route as MembersApplicationIdRouteImport } from './routes/members.$applicationId'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SettingsAccountRouteImport } from './routes/settings.account'
import { Route as SettingsAppearanceRouteImport } from './routes/settings.appearance'
import { Route as SettingsAutomationsRouteImport } from './routes/settings.automations'
import { Route as SettingsClubRouteImport } from './routes/settings.club'
import { Route as SettingsPrivacyRouteImport } from './routes/settings.privacy'
import { Route as SettingsRbacRouteImport } from './routes/settings.rbac'
import { Route as UserManagementIndexRouteImport } from './routes/user-management.index'
import { Route as UserManagementUserAccountIdRouteImport } from './routes/user-management.$userAccountId'
import { Route as ManageCommitteeMeetingsIndexRouteImport } from './routes/manage-committee.meetings.index'
import { Route as ManageCommitteeMeetingsHistoryRouteImport } from './routes/manage-committee.meetings.history'
import { Route as ManageCommitteeMeetingsInterviewRouteImport } from './routes/manage-committee.meetings.interview'
import { Route as ManageCommitteeMeetingsPendingRouteImport } from './routes/manage-committee.meetings.pending'
import { Route as ManageCommitteeMeetingsWaitingRouteImport } from './routes/manage-committee.meetings.waiting'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccommodationRoute = AccommodationRouteImport.update({
  id: '/accommodation',
  path: '/accommodation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationRoute = ApplicationRouteImport.update({
  id: '/application',
  path: '/application',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const CommitteeBallotRoute = CommitteeBallotRouteImport.update({
  id: '/committee-ballot',
  path: '/committee-ballot',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ElectionRoute = ElectionRouteImport.update({
  id: '/election',
  path: '/election',
  getParentRoute: () => rootRouteImport,
} as any)
const EndorsementsRoute = EndorsementsRouteImport.update({
  id: '/endorsements',
  path: '/endorsements',
  getParentRoute: () => rootRouteImport,
} as any)
const ExistingMembersRoute = ExistingMembersRouteImport.update({
  id: '/existing-members',
  path: '/existing-members',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceRoute = GovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestsRoute = GuestsRouteImport.update({
  id: '/guests',
  path: '/guests',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageCommitteeRoute = ManageCommitteeRouteImport.update({
  id: '/manage-committee',
  path: '/manage-committee',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceptionRoute = ReceptionRouteImport.update({
  id: '/reception',
  path: '/reception',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterMemberRoute = RegisterMemberRouteImport.update({
  id: '/register-member',
  path: '/register-member',
  getParentRoute: () => rootRouteImport,
} as any)
const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const UserManagementRoute = UserManagementRouteImport.update({
  id: '/user-management',
  path: '/user-management',
  getParentRoute: () => rootRouteImport,
} as any)
const CommitteeBallotIndexRoute = CommitteeBallotIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CommitteeBallotRoute,
} as any)
const CommitteeBallotAttendanceRoute =
  CommitteeBallotAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => CommitteeBallotRoute,
  } as any)
const CommitteeBallotCandidatesRoute =
  CommitteeBallotCandidatesRouteImport.update({
    id: '/candidates',
    path: '/candidates',
    getParentRoute: () => CommitteeBallotRoute,
  } as any)
const CommitteeBallotPendingRoute = CommitteeBallotPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => CommitteeBallotRoute,
} as any)
const ExistingMembersIndexRoute = ExistingMembersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExistingMembersRoute,
} as any)
const ExistingMembersAccountIdRoute =
  ExistingMembersAccountIdRouteImport.update({
    id: '/$accountId',
    path: '/$accountId',
    getParentRoute: () => ExistingMembersRoute,
  } as any)
const ManageCommitteeIndexRoute = ManageCommitteeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManageCommitteeRoute,
} as any)
const ManageCommitteeCurrentTermRoute =
  ManageCommitteeCurrentTermRouteImport.update({
    id: '/current-term',
    path: '/current-term',
    getParentRoute: () => ManageCommitteeRoute,
  } as any)
const ManageCommitteeMeetingsRoute = ManageCommitteeMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => ManageCommitteeRoute,
} as any)
const ManageCommitteeMembersRoute = ManageCommitteeMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => ManageCommitteeRoute,
} as any)
const ManageCommitteeNewTermRoute = ManageCommitteeNewTermRouteImport.update({
  id: '/new-term',
  path: '/new-term',
  getParentRoute: () => ManageCommitteeRoute,
} as any)
const MembersIndexRoute = MembersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MembersRoute,
} as any)
const MembersApplicationIdRoute = MembersApplicationIdRouteImport.update({
  id: '/$applicationId',
  path: '/$applicationId',
  getParentRoute: () => MembersRoute,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAccountRoute = SettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAutomationsRoute = SettingsAutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsClubRoute = SettingsClubRouteImport.update({
  id: '/club',
  path: '/club',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPrivacyRoute = SettingsPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsRbacRoute = SettingsRbacRouteImport.update({
  id: '/rbac',
  path: '/rbac',
  getParentRoute: () => SettingsRoute,
} as any)
const UserManagementIndexRoute = UserManagementIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserManagementRoute,
} as any)
const UserManagementUserAccountIdRoute =
  UserManagementUserAccountIdRouteImport.update({
    id: '/$userAccountId',
    path: '/$userAccountId',
    getParentRoute: () => UserManagementRoute,
  } as any)
const ManageCommitteeMeetingsIndexRoute =
  ManageCommitteeMeetingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ManageCommitteeMeetingsRoute,
  } as any)
const ManageCommitteeMeetingsHistoryRoute =
  ManageCommitteeMeetingsHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => ManageCommitteeMeetingsRoute,
  } as any)
const ManageCommitteeMeetingsInterviewRoute =
  ManageCommitteeMeetingsInterviewRouteImport.update({
    id: '/interview',
    path: '/interview',
    getParentRoute: () => ManageCommitteeMeetingsRoute,
  } as any)
const ManageCommitteeMeetingsPendingRoute =
  ManageCommitteeMeetingsPendingRouteImport.update({
    id: '/pending',
    path: '/pending',
    getParentRoute: () => ManageCommitteeMeetingsRoute,
  } as any)
const ManageCommitteeMeetingsWaitingRoute =
  ManageCommitteeMeetingsWaitingRouteImport.update({
    id: '/waiting',
    path: '/waiting',
    getParentRoute: () => ManageCommitteeMeetingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accommodation': typeof AccommodationRoute
  '/admin': typeof AdminRoute
  '/application': typeof ApplicationRoute
  '/applications': typeof ApplicationsRoute
  '/committee-ballot': typeof CommitteeBallotRouteWithChildren
  '/documents': typeof DocumentsRoute
  '/election': typeof ElectionRoute
  '/endorsements': typeof EndorsementsRoute
  '/existing-members': typeof ExistingMembersRouteWithChildren
  '/finance': typeof FinanceRoute
  '/governance': typeof GovernanceRoute
  '/guests': typeof GuestsRoute
  '/login': typeof LoginRoute
  '/manage-committee': typeof ManageCommitteeRouteWithChildren
  '/members': typeof MembersRouteWithChildren
  '/payment': typeof PaymentRoute
  '/profile': typeof ProfileRoute
  '/reception': typeof ReceptionRoute
  '/register': typeof RegisterRoute
  '/register-member': typeof RegisterMemberRoute
  '/set-password': typeof SetPasswordRoute
  '/settings': typeof SettingsRouteWithChildren
  '/support': typeof SupportRoute
  '/user-management': typeof UserManagementRouteWithChildren
  '/committee-ballot/attendance': typeof CommitteeBallotAttendanceRoute
  '/committee-ballot/candidates': typeof CommitteeBallotCandidatesRoute
  '/committee-ballot/pending': typeof CommitteeBallotPendingRoute
  '/existing-members/$accountId': typeof ExistingMembersAccountIdRoute
  '/manage-committee/current-term': typeof ManageCommitteeCurrentTermRoute
  '/manage-committee/meetings': typeof ManageCommitteeMeetingsRouteWithChildren
  '/manage-committee/members': typeof ManageCommitteeMembersRoute
  '/manage-committee/new-term': typeof ManageCommitteeNewTermRoute
  '/members/$applicationId': typeof MembersApplicationIdRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/automations': typeof SettingsAutomationsRoute
  '/settings/club': typeof SettingsClubRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/rbac': typeof SettingsRbacRoute
  '/user-management/$userAccountId': typeof UserManagementUserAccountIdRoute
  '/committee-ballot/': typeof CommitteeBallotIndexRoute
  '/existing-members/': typeof ExistingMembersIndexRoute
  '/manage-committee/': typeof ManageCommitteeIndexRoute
  '/members/': typeof MembersIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/user-management/': typeof UserManagementIndexRoute
  '/manage-committee/meetings/history': typeof ManageCommitteeMeetingsHistoryRoute
  '/manage-committee/meetings/interview': typeof ManageCommitteeMeetingsInterviewRoute
  '/manage-committee/meetings/pending': typeof ManageCommitteeMeetingsPendingRoute
  '/manage-committee/meetings/waiting': typeof ManageCommitteeMeetingsWaitingRoute
  '/manage-committee/meetings/': typeof ManageCommitteeMeetingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accommodation': typeof AccommodationRoute
  '/admin': typeof AdminRoute
  '/application': typeof ApplicationRoute
  '/applications': typeof ApplicationsRoute
  '/documents': typeof DocumentsRoute
  '/election': typeof ElectionRoute
  '/endorsements': typeof EndorsementsRoute
  '/finance': typeof FinanceRoute
  '/governance': typeof GovernanceRoute
  '/guests': typeof GuestsRoute
  '/login': typeof LoginRoute
  '/payment': typeof PaymentRoute
  '/profile': typeof ProfileRoute
  '/reception': typeof ReceptionRoute
  '/register': typeof RegisterRoute
  '/register-member': typeof RegisterMemberRoute
  '/set-password': typeof SetPasswordRoute
  '/support': typeof SupportRoute
  '/committee-ballot/attendance': typeof CommitteeBallotAttendanceRoute
  '/committee-ballot/candidates': typeof CommitteeBallotCandidatesRoute
  '/committee-ballot/pending': typeof CommitteeBallotPendingRoute
  '/existing-members/$accountId': typeof ExistingMembersAccountIdRoute
  '/manage-committee/current-term': typeof ManageCommitteeCurrentTermRoute
  '/manage-committee/members': typeof ManageCommitteeMembersRoute
  '/manage-committee/new-term': typeof ManageCommitteeNewTermRoute
  '/members/$applicationId': typeof MembersApplicationIdRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/automations': typeof SettingsAutomationsRoute
  '/settings/club': typeof SettingsClubRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/rbac': typeof SettingsRbacRoute
  '/user-management/$userAccountId': typeof UserManagementUserAccountIdRoute
  '/committee-ballot': typeof CommitteeBallotIndexRoute
  '/existing-members': typeof ExistingMembersIndexRoute
  '/manage-committee': typeof ManageCommitteeIndexRoute
  '/members': typeof MembersIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/user-management': typeof UserManagementIndexRoute
  '/manage-committee/meetings/history': typeof ManageCommitteeMeetingsHistoryRoute
  '/manage-committee/meetings/interview': typeof ManageCommitteeMeetingsInterviewRoute
  '/manage-committee/meetings/pending': typeof ManageCommitteeMeetingsPendingRoute
  '/manage-committee/meetings/waiting': typeof ManageCommitteeMeetingsWaitingRoute
  '/manage-committee/meetings': typeof ManageCommitteeMeetingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accommodation': typeof AccommodationRoute
  '/admin': typeof AdminRoute
  '/application': typeof ApplicationRoute
  '/applications': typeof ApplicationsRoute
  '/committee-ballot': typeof CommitteeBallotRouteWithChildren
  '/documents': typeof DocumentsRoute
  '/election': typeof ElectionRoute
  '/endorsements': typeof EndorsementsRoute
  '/existing-members': typeof ExistingMembersRouteWithChildren
  '/finance': typeof FinanceRoute
  '/governance': typeof GovernanceRoute
  '/guests': typeof GuestsRoute
  '/login': typeof LoginRoute
  '/manage-committee': typeof ManageCommitteeRouteWithChildren
  '/members': typeof MembersRouteWithChildren
  '/payment': typeof PaymentRoute
  '/profile': typeof ProfileRoute
  '/reception': typeof ReceptionRoute
  '/register': typeof RegisterRoute
  '/register-member': typeof RegisterMemberRoute
  '/set-password': typeof SetPasswordRoute
  '/settings': typeof SettingsRouteWithChildren
  '/support': typeof SupportRoute
  '/user-management': typeof UserManagementRouteWithChildren
  '/committee-ballot/attendance': typeof CommitteeBallotAttendanceRoute
  '/committee-ballot/candidates': typeof CommitteeBallotCandidatesRoute
  '/committee-ballot/pending': typeof CommitteeBallotPendingRoute
  '/existing-members/$accountId': typeof ExistingMembersAccountIdRoute
  '/manage-committee/current-term': typeof ManageCommitteeCurrentTermRoute
  '/manage-committee/meetings': typeof ManageCommitteeMeetingsRouteWithChildren
  '/manage-committee/members': typeof ManageCommitteeMembersRoute
  '/manage-committee/new-term': typeof ManageCommitteeNewTermRoute
  '/members/$applicationId': typeof MembersApplicationIdRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/automations': typeof SettingsAutomationsRoute
  '/settings/club': typeof SettingsClubRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/rbac': typeof SettingsRbacRoute
  '/user-management/$userAccountId': typeof UserManagementUserAccountIdRoute
  '/committee-ballot/': typeof CommitteeBallotIndexRoute
  '/existing-members/': typeof ExistingMembersIndexRoute
  '/manage-committee/': typeof ManageCommitteeIndexRoute
  '/members/': typeof MembersIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/user-management/': typeof UserManagementIndexRoute
  '/manage-committee/meetings/history': typeof ManageCommitteeMeetingsHistoryRoute
  '/manage-committee/meetings/interview': typeof ManageCommitteeMeetingsInterviewRoute
  '/manage-committee/meetings/pending': typeof ManageCommitteeMeetingsPendingRoute
  '/manage-committee/meetings/waiting': typeof ManageCommitteeMeetingsWaitingRoute
  '/manage-committee/meetings/': typeof ManageCommitteeMeetingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accommodation'
    | '/admin'
    | '/application'
    | '/applications'
    | '/committee-ballot'
    | '/documents'
    | '/election'
    | '/endorsements'
    | '/existing-members'
    | '/finance'
    | '/governance'
    | '/guests'
    | '/login'
    | '/manage-committee'
    | '/members'
    | '/payment'
    | '/profile'
    | '/reception'
    | '/register'
    | '/register-member'
    | '/set-password'
    | '/settings'
    | '/support'
    | '/user-management'
    | '/committee-ballot/attendance'
    | '/committee-ballot/candidates'
    | '/committee-ballot/pending'
    | '/existing-members/$accountId'
    | '/manage-committee/current-term'
    | '/manage-committee/meetings'
    | '/manage-committee/members'
    | '/manage-committee/new-term'
    | '/members/$applicationId'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/automations'
    | '/settings/club'
    | '/settings/privacy'
    | '/settings/rbac'
    | '/user-management/$userAccountId'
    | '/committee-ballot/'
    | '/existing-members/'
    | '/manage-committee/'
    | '/members/'
    | '/settings/'
    | '/user-management/'
    | '/manage-committee/meetings/history'
    | '/manage-committee/meetings/interview'
    | '/manage-committee/meetings/pending'
    | '/manage-committee/meetings/waiting'
    | '/manage-committee/meetings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accommodation'
    | '/admin'
    | '/application'
    | '/applications'
    | '/documents'
    | '/election'
    | '/endorsements'
    | '/finance'
    | '/governance'
    | '/guests'
    | '/login'
    | '/payment'
    | '/profile'
    | '/reception'
    | '/register'
    | '/register-member'
    | '/set-password'
    | '/support'
    | '/committee-ballot/attendance'
    | '/committee-ballot/candidates'
    | '/committee-ballot/pending'
    | '/existing-members/$accountId'
    | '/manage-committee/current-term'
    | '/manage-committee/members'
    | '/manage-committee/new-term'
    | '/members/$applicationId'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/automations'
    | '/settings/club'
    | '/settings/privacy'
    | '/settings/rbac'
    | '/user-management/$userAccountId'
    | '/committee-ballot'
    | '/existing-members'
    | '/manage-committee'
    | '/members'
    | '/settings'
    | '/user-management'
    | '/manage-committee/meetings/history'
    | '/manage-committee/meetings/interview'
    | '/manage-committee/meetings/pending'
    | '/manage-committee/meetings/waiting'
    | '/manage-committee/meetings'
  id:
    | '__root__'
    | '/'
    | '/accommodation'
    | '/admin'
    | '/application'
    | '/applications'
    | '/committee-ballot'
    | '/documents'
    | '/election'
    | '/endorsements'
    | '/existing-members'
    | '/finance'
    | '/governance'
    | '/guests'
    | '/login'
    | '/manage-committee'
    | '/members'
    | '/payment'
    | '/profile'
    | '/reception'
    | '/register'
    | '/register-member'
    | '/set-password'
    | '/settings'
    | '/support'
    | '/user-management'
    | '/committee-ballot/attendance'
    | '/committee-ballot/candidates'
    | '/committee-ballot/pending'
    | '/existing-members/$accountId'
    | '/manage-committee/current-term'
    | '/manage-committee/meetings'
    | '/manage-committee/members'
    | '/manage-committee/new-term'
    | '/members/$applicationId'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/automations'
    | '/settings/club'
    | '/settings/privacy'
    | '/settings/rbac'
    | '/user-management/$userAccountId'
    | '/committee-ballot/'
    | '/existing-members/'
    | '/manage-committee/'
    | '/members/'
    | '/settings/'
    | '/user-management/'
    | '/manage-committee/meetings/history'
    | '/manage-committee/meetings/interview'
    | '/manage-committee/meetings/pending'
    | '/manage-committee/meetings/waiting'
    | '/manage-committee/meetings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccommodationRoute: typeof AccommodationRoute
  AdminRoute: typeof AdminRoute
  ApplicationRoute: typeof ApplicationRoute
  ApplicationsRoute: typeof ApplicationsRoute
  CommitteeBallotRoute: typeof CommitteeBallotRouteWithChildren
  DocumentsRoute: typeof DocumentsRoute
  ElectionRoute: typeof ElectionRoute
  EndorsementsRoute: typeof EndorsementsRoute
  ExistingMembersRoute: typeof ExistingMembersRouteWithChildren
  FinanceRoute: typeof FinanceRoute
  GovernanceRoute: typeof GovernanceRoute
  GuestsRoute: typeof GuestsRoute
  LoginRoute: typeof LoginRoute
  ManageCommitteeRoute: typeof ManageCommitteeRouteWithChildren
  MembersRoute: typeof MembersRouteWithChildren
  PaymentRoute: typeof PaymentRoute
  ProfileRoute: typeof ProfileRoute
  ReceptionRoute: typeof ReceptionRoute
  RegisterRoute: typeof RegisterRoute
  RegisterMemberRoute: typeof RegisterMemberRoute
  SetPasswordRoute: typeof SetPasswordRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SupportRoute: typeof SupportRoute
  UserManagementRoute: typeof UserManagementRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accommodation': {
      id: '/accommodation'
      path: '/accommodation'
      fullPath: '/accommodation'
      preLoaderRoute: typeof AccommodationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/application': {
      id: '/application'
      path: '/application'
      fullPath: '/application'
      preLoaderRoute: typeof ApplicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/committee-ballot': {
      id: '/committee-ballot'
      path: '/committee-ballot'
      fullPath: '/committee-ballot'
      preLoaderRoute: typeof CommitteeBallotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/election': {
      id: '/election'
      path: '/election'
      fullPath: '/election'
      preLoaderRoute: typeof ElectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/endorsements': {
      id: '/endorsements'
      path: '/endorsements'
      fullPath: '/endorsements'
      preLoaderRoute: typeof EndorsementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/existing-members': {
      id: '/existing-members'
      path: '/existing-members'
      fullPath: '/existing-members'
      preLoaderRoute: typeof ExistingMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance': {
      id: '/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof GovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guests': {
      id: '/guests'
      path: '/guests'
      fullPath: '/guests'
      preLoaderRoute: typeof GuestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage-committee': {
      id: '/manage-committee'
      path: '/manage-committee'
      fullPath: '/manage-committee'
      preLoaderRoute: typeof ManageCommitteeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reception': {
      id: '/reception'
      path: '/reception'
      fullPath: '/reception'
      preLoaderRoute: typeof ReceptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-member': {
      id: '/register-member'
      path: '/register-member'
      fullPath: '/register-member'
      preLoaderRoute: typeof RegisterMemberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-management': {
      id: '/user-management'
      path: '/user-management'
      fullPath: '/user-management'
      preLoaderRoute: typeof UserManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/committee-ballot/': {
      id: '/committee-ballot/'
      path: '/'
      fullPath: '/committee-ballot/'
      preLoaderRoute: typeof CommitteeBallotIndexRouteImport
      parentRoute: typeof CommitteeBallotRoute
    }
    '/committee-ballot/attendance': {
      id: '/committee-ballot/attendance'
      path: '/attendance'
      fullPath: '/committee-ballot/attendance'
      preLoaderRoute: typeof CommitteeBallotAttendanceRouteImport
      parentRoute: typeof CommitteeBallotRoute
    }
    '/committee-ballot/candidates': {
      id: '/committee-ballot/candidates'
      path: '/candidates'
      fullPath: '/committee-ballot/candidates'
      preLoaderRoute: typeof CommitteeBallotCandidatesRouteImport
      parentRoute: typeof CommitteeBallotRoute
    }
    '/committee-ballot/pending': {
      id: '/committee-ballot/pending'
      path: '/pending'
      fullPath: '/committee-ballot/pending'
      preLoaderRoute: typeof CommitteeBallotPendingRouteImport
      parentRoute: typeof CommitteeBallotRoute
    }
    '/existing-members/': {
      id: '/existing-members/'
      path: '/'
      fullPath: '/existing-members/'
      preLoaderRoute: typeof ExistingMembersIndexRouteImport
      parentRoute: typeof ExistingMembersRoute
    }
    '/existing-members/$accountId': {
      id: '/existing-members/$accountId'
      path: '/$accountId'
      fullPath: '/existing-members/$accountId'
      preLoaderRoute: typeof ExistingMembersAccountIdRouteImport
      parentRoute: typeof ExistingMembersRoute
    }
    '/manage-committee/': {
      id: '/manage-committee/'
      path: '/'
      fullPath: '/manage-committee/'
      preLoaderRoute: typeof ManageCommitteeIndexRouteImport
      parentRoute: typeof ManageCommitteeRoute
    }
    '/manage-committee/current-term': {
      id: '/manage-committee/current-term'
      path: '/current-term'
      fullPath: '/manage-committee/current-term'
      preLoaderRoute: typeof ManageCommitteeCurrentTermRouteImport
      parentRoute: typeof ManageCommitteeRoute
    }
    '/manage-committee/meetings': {
      id: '/manage-committee/meetings'
      path: '/meetings'
      fullPath: '/manage-committee/meetings'
      preLoaderRoute: typeof ManageCommitteeMeetingsRouteImport
      parentRoute: typeof ManageCommitteeRoute
    }
    '/manage-committee/members': {
      id: '/manage-committee/members'
      path: '/members'
      fullPath: '/manage-committee/members'
      preLoaderRoute: typeof ManageCommitteeMembersRouteImport
      parentRoute: typeof ManageCommitteeRoute
    }
    '/manage-committee/new-term': {
      id: '/manage-committee/new-term'
      path: '/new-term'
      fullPath: '/manage-committee/new-term'
      preLoaderRoute: typeof ManageCommitteeNewTermRouteImport
      parentRoute: typeof ManageCommitteeRoute
    }
    '/members/': {
      id: '/members/'
      path: '/'
      fullPath: '/members/'
      preLoaderRoute: typeof MembersIndexRouteImport
      parentRoute: typeof MembersRoute
    }
    '/members/$applicationId': {
      id: '/members/$applicationId'
      path: '/$applicationId'
      fullPath: '/members/$applicationId'
      preLoaderRoute: typeof MembersApplicationIdRouteImport
      parentRoute: typeof MembersRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/account': {
      id: '/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof SettingsAccountRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/automations': {
      id: '/settings/automations'
      path: '/automations'
      fullPath: '/settings/automations'
      preLoaderRoute: typeof SettingsAutomationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/club': {
      id: '/settings/club'
      path: '/club'
      fullPath: '/settings/club'
      preLoaderRoute: typeof SettingsClubRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/privacy': {
      id: '/settings/privacy'
      path: '/privacy'
      fullPath: '/settings/privacy'
      preLoaderRoute: typeof SettingsPrivacyRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/rbac': {
      id: '/settings/rbac'
      path: '/rbac'
      fullPath: '/settings/rbac'
      preLoaderRoute: typeof SettingsRbacRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/user-management/': {
      id: '/user-management/'
      path: '/'
      fullPath: '/user-management/'
      preLoaderRoute: typeof UserManagementIndexRouteImport
      parentRoute: typeof UserManagementRoute
    }
    '/user-management/$userAccountId': {
      id: '/user-management/$userAccountId'
      path: '/$userAccountId'
      fullPath: '/user-management/$userAccountId'
      preLoaderRoute: typeof UserManagementUserAccountIdRouteImport
      parentRoute: typeof UserManagementRoute
    }
    '/manage-committee/meetings/': {
      id: '/manage-committee/meetings/'
      path: '/'
      fullPath: '/manage-committee/meetings/'
      preLoaderRoute: typeof ManageCommitteeMeetingsIndexRouteImport
      parentRoute: typeof ManageCommitteeMeetingsRoute
    }
    '/manage-committee/meetings/history': {
      id: '/manage-committee/meetings/history'
      path: '/history'
      fullPath: '/manage-committee/meetings/history'
      preLoaderRoute: typeof ManageCommitteeMeetingsHistoryRouteImport
      parentRoute: typeof ManageCommitteeMeetingsRoute
    }
    '/manage-committee/meetings/interview': {
      id: '/manage-committee/meetings/interview'
      path: '/interview'
      fullPath: '/manage-committee/meetings/interview'
      preLoaderRoute: typeof ManageCommitteeMeetingsInterviewRouteImport
      parentRoute: typeof ManageCommitteeMeetingsRoute
    }
    '/manage-committee/meetings/pending': {
      id: '/manage-committee/meetings/pending'
      path: '/pending'
      fullPath: '/manage-committee/meetings/pending'
      preLoaderRoute: typeof ManageCommitteeMeetingsPendingRouteImport
      parentRoute: typeof ManageCommitteeMeetingsRoute
    }
    '/manage-committee/meetings/waiting': {
      id: '/manage-committee/meetings/waiting'
      path: '/waiting'
      fullPath: '/manage-committee/meetings/waiting'
      preLoaderRoute: typeof ManageCommitteeMeetingsWaitingRouteImport
      parentRoute: typeof ManageCommitteeMeetingsRoute
    }
  }
}

interface CommitteeBallotRouteChildren {
  CommitteeBallotAttendanceRoute: typeof CommitteeBallotAttendanceRoute
  CommitteeBallotCandidatesRoute: typeof CommitteeBallotCandidatesRoute
  CommitteeBallotPendingRoute: typeof CommitteeBallotPendingRoute
  CommitteeBallotIndexRoute: typeof CommitteeBallotIndexRoute
}

const CommitteeBallotRouteChildren: CommitteeBallotRouteChildren = {
  CommitteeBallotAttendanceRoute: CommitteeBallotAttendanceRoute,
  CommitteeBallotCandidatesRoute: CommitteeBallotCandidatesRoute,
  CommitteeBallotPendingRoute: CommitteeBallotPendingRoute,
  CommitteeBallotIndexRoute: CommitteeBallotIndexRoute,
}

const CommitteeBallotRouteWithChildren = CommitteeBallotRoute._addFileChildren(
  CommitteeBallotRouteChildren,
)

interface ExistingMembersRouteChildren {
  ExistingMembersAccountIdRoute: typeof ExistingMembersAccountIdRoute
  ExistingMembersIndexRoute: typeof ExistingMembersIndexRoute
}

const ExistingMembersRouteChildren: ExistingMembersRouteChildren = {
  ExistingMembersAccountIdRoute: ExistingMembersAccountIdRoute,
  ExistingMembersIndexRoute: ExistingMembersIndexRoute,
}

const ExistingMembersRouteWithChildren = ExistingMembersRoute._addFileChildren(
  ExistingMembersRouteChildren,
)

interface ManageCommitteeMeetingsRouteChildren {
  ManageCommitteeMeetingsHistoryRoute: typeof ManageCommitteeMeetingsHistoryRoute
  ManageCommitteeMeetingsInterviewRoute: typeof ManageCommitteeMeetingsInterviewRoute
  ManageCommitteeMeetingsPendingRoute: typeof ManageCommitteeMeetingsPendingRoute
  ManageCommitteeMeetingsWaitingRoute: typeof ManageCommitteeMeetingsWaitingRoute
  ManageCommitteeMeetingsIndexRoute: typeof ManageCommitteeMeetingsIndexRoute
}

const ManageCommitteeMeetingsRouteChildren: ManageCommitteeMeetingsRouteChildren =
  {
    ManageCommitteeMeetingsHistoryRoute: ManageCommitteeMeetingsHistoryRoute,
    ManageCommitteeMeetingsInterviewRoute:
      ManageCommitteeMeetingsInterviewRoute,
    ManageCommitteeMeetingsPendingRoute: ManageCommitteeMeetingsPendingRoute,
    ManageCommitteeMeetingsWaitingRoute: ManageCommitteeMeetingsWaitingRoute,
    ManageCommitteeMeetingsIndexRoute: ManageCommitteeMeetingsIndexRoute,
  }

const ManageCommitteeMeetingsRouteWithChildren =
  ManageCommitteeMeetingsRoute._addFileChildren(
    ManageCommitteeMeetingsRouteChildren,
  )

interface ManageCommitteeRouteChildren {
  ManageCommitteeCurrentTermRoute: typeof ManageCommitteeCurrentTermRoute
  ManageCommitteeMeetingsRoute: typeof ManageCommitteeMeetingsRouteWithChildren
  ManageCommitteeMembersRoute: typeof ManageCommitteeMembersRoute
  ManageCommitteeNewTermRoute: typeof ManageCommitteeNewTermRoute
  ManageCommitteeIndexRoute: typeof ManageCommitteeIndexRoute
}

const ManageCommitteeRouteChildren: ManageCommitteeRouteChildren = {
  ManageCommitteeCurrentTermRoute: ManageCommitteeCurrentTermRoute,
  ManageCommitteeMeetingsRoute: ManageCommitteeMeetingsRouteWithChildren,
  ManageCommitteeMembersRoute: ManageCommitteeMembersRoute,
  ManageCommitteeNewTermRoute: ManageCommitteeNewTermRoute,
  ManageCommitteeIndexRoute: ManageCommitteeIndexRoute,
}

const ManageCommitteeRouteWithChildren = ManageCommitteeRoute._addFileChildren(
  ManageCommitteeRouteChildren,
)

interface MembersRouteChildren {
  MembersApplicationIdRoute: typeof MembersApplicationIdRoute
  MembersIndexRoute: typeof MembersIndexRoute
}

const MembersRouteChildren: MembersRouteChildren = {
  MembersApplicationIdRoute: MembersApplicationIdRoute,
  MembersIndexRoute: MembersIndexRoute,
}

const MembersRouteWithChildren =
  MembersRoute._addFileChildren(MembersRouteChildren)

interface SettingsRouteChildren {
  SettingsAccountRoute: typeof SettingsAccountRoute
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsAutomationsRoute: typeof SettingsAutomationsRoute
  SettingsClubRoute: typeof SettingsClubRoute
  SettingsPrivacyRoute: typeof SettingsPrivacyRoute
  SettingsRbacRoute: typeof SettingsRbacRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAccountRoute: SettingsAccountRoute,
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsAutomationsRoute: SettingsAutomationsRoute,
  SettingsClubRoute: SettingsClubRoute,
  SettingsPrivacyRoute: SettingsPrivacyRoute,
  SettingsRbacRoute: SettingsRbacRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface UserManagementRouteChildren {
  UserManagementUserAccountIdRoute: typeof UserManagementUserAccountIdRoute
  UserManagementIndexRoute: typeof UserManagementIndexRoute
}

const UserManagementRouteChildren: UserManagementRouteChildren = {
  UserManagementUserAccountIdRoute: UserManagementUserAccountIdRoute,
  UserManagementIndexRoute: UserManagementIndexRoute,
}

const UserManagementRouteWithChildren = UserManagementRoute._addFileChildren(
  UserManagementRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccommodationRoute: AccommodationRoute,
  AdminRoute: AdminRoute,
  ApplicationRoute: ApplicationRoute,
  ApplicationsRoute: ApplicationsRoute,
  CommitteeBallotRoute: CommitteeBallotRouteWithChildren,
  DocumentsRoute: DocumentsRoute,
  ElectionRoute: ElectionRoute,
  EndorsementsRoute: EndorsementsRoute,
  ExistingMembersRoute: ExistingMembersRouteWithChildren,
  FinanceRoute: FinanceRoute,
  GovernanceRoute: GovernanceRoute,
  GuestsRoute: GuestsRoute,
  LoginRoute: LoginRoute,
  ManageCommitteeRoute: ManageCommitteeRouteWithChildren,
  MembersRoute: MembersRouteWithChildren,
  PaymentRoute: PaymentRoute,
  ProfileRoute: ProfileRoute,
  ReceptionRoute: ReceptionRoute,
  RegisterRoute: RegisterRoute,
  RegisterMemberRoute: RegisterMemberRoute,
  SetPasswordRoute: SetPasswordRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SupportRoute: SupportRoute,
  UserManagementRoute: UserManagementRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
