/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccommodationRouteImport } from './routes/accommodation'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ApplicationRouteImport } from './routes/application'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as CommitteeBallotRouteImport } from './routes/committee-ballot'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as ElectionRouteImport } from './routes/election'
import { Route as EndorsementsRouteImport } from './routes/endorsements'
import { Route as ExistingMembersRouteImport } from './routes/existing-members'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as GovernanceRouteImport } from './routes/governance'
import { Route as GuestsRouteImport } from './routes/guests'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ManageCommitteeRouteImport } from './routes/manage-committee'
import { Route as MembersRouteImport } from './routes/members'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RegisterMemberRouteImport } from './routes/register-member'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SupportRouteImport } from './routes/support'
import { Route as UserManagementRouteImport } from './routes/user-management'
import { Route as ExistingMembersIndexRouteImport } from './routes/existing-members.index'
import { Route as ExistingMembersAccountIdRouteImport } from './routes/existing-members.$accountId'
import { Route as MembersIndexRouteImport } from './routes/members.index'
import { Route as MembersApplicationIdRouteImport } from './routes/members.$applicationId'
import { Route as UserManagementIndexRouteImport } from './routes/user-management.index'
import { Route as UserManagementUserAccountIdRouteImport } from './routes/user-management.$userAccountId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccommodationRoute = AccommodationRouteImport.update({
  id: '/accommodation',
  path: '/accommodation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationRoute = ApplicationRouteImport.update({
  id: '/application',
  path: '/application',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const CommitteeBallotRoute = CommitteeBallotRouteImport.update({
  id: '/committee-ballot',
  path: '/committee-ballot',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ElectionRoute = ElectionRouteImport.update({
  id: '/election',
  path: '/election',
  getParentRoute: () => rootRouteImport,
} as any)
const EndorsementsRoute = EndorsementsRouteImport.update({
  id: '/endorsements',
  path: '/endorsements',
  getParentRoute: () => rootRouteImport,
} as any)
const ExistingMembersRoute = ExistingMembersRouteImport.update({
  id: '/existing-members',
  path: '/existing-members',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceRoute = GovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestsRoute = GuestsRouteImport.update({
  id: '/guests',
  path: '/guests',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageCommitteeRoute = ManageCommitteeRouteImport.update({
  id: '/manage-committee',
  path: '/manage-committee',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterMemberRoute = RegisterMemberRouteImport.update({
  id: '/register-member',
  path: '/register-member',
  getParentRoute: () => rootRouteImport,
} as any)
const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const UserManagementRoute = UserManagementRouteImport.update({
  id: '/user-management',
  path: '/user-management',
  getParentRoute: () => rootRouteImport,
} as any)
const ExistingMembersIndexRoute = ExistingMembersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExistingMembersRoute,
} as any)
const ExistingMembersAccountIdRoute =
  ExistingMembersAccountIdRouteImport.update({
    id: '/$accountId',
    path: '/$accountId',
    getParentRoute: () => ExistingMembersRoute,
  } as any)
const MembersIndexRoute = MembersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MembersRoute,
} as any)
const MembersApplicationIdRoute = MembersApplicationIdRouteImport.update({
  id: '/$applicationId',
  path: '/$applicationId',
  getParentRoute: () => MembersRoute,
} as any)
const UserManagementIndexRoute = UserManagementIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserManagementRoute,
} as any)
const UserManagementUserAccountIdRoute =
  UserManagementUserAccountIdRouteImport.update({
    id: '/$userAccountId',
    path: '/$userAccountId',
    getParentRoute: () => UserManagementRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accommodation': typeof AccommodationRoute
  '/admin': typeof AdminRoute
  '/application': typeof ApplicationRoute
  '/applications': typeof ApplicationsRoute
  '/committee-ballot': typeof CommitteeBallotRoute
  '/documents': typeof DocumentsRoute
  '/election': typeof ElectionRoute
  '/endorsements': typeof EndorsementsRoute
  '/existing-members': typeof ExistingMembersRouteWithChildren
  '/finance': typeof FinanceRoute
  '/governance': typeof GovernanceRoute
  '/guests': typeof GuestsRoute
  '/login': typeof LoginRoute
  '/manage-committee': typeof ManageCommitteeRoute
  '/members': typeof MembersRouteWithChildren
  '/payment': typeof PaymentRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/register-member': typeof RegisterMemberRoute
  '/set-password': typeof SetPasswordRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/user-management': typeof UserManagementRouteWithChildren
  '/existing-members/$accountId': typeof ExistingMembersAccountIdRoute
  '/members/$applicationId': typeof MembersApplicationIdRoute
  '/user-management/$userAccountId': typeof UserManagementUserAccountIdRoute
  '/existing-members/': typeof ExistingMembersIndexRoute
  '/members/': typeof MembersIndexRoute
  '/user-management/': typeof UserManagementIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accommodation': typeof AccommodationRoute
  '/admin': typeof AdminRoute
  '/application': typeof ApplicationRoute
  '/applications': typeof ApplicationsRoute
  '/committee-ballot': typeof CommitteeBallotRoute
  '/documents': typeof DocumentsRoute
  '/election': typeof ElectionRoute
  '/endorsements': typeof EndorsementsRoute
  '/finance': typeof FinanceRoute
  '/governance': typeof GovernanceRoute
  '/guests': typeof GuestsRoute
  '/login': typeof LoginRoute
  '/manage-committee': typeof ManageCommitteeRoute
  '/payment': typeof PaymentRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/register-member': typeof RegisterMemberRoute
  '/set-password': typeof SetPasswordRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/existing-members/$accountId': typeof ExistingMembersAccountIdRoute
  '/members/$applicationId': typeof MembersApplicationIdRoute
  '/user-management/$userAccountId': typeof UserManagementUserAccountIdRoute
  '/existing-members': typeof ExistingMembersIndexRoute
  '/members': typeof MembersIndexRoute
  '/user-management': typeof UserManagementIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accommodation': typeof AccommodationRoute
  '/admin': typeof AdminRoute
  '/application': typeof ApplicationRoute
  '/applications': typeof ApplicationsRoute
  '/committee-ballot': typeof CommitteeBallotRoute
  '/documents': typeof DocumentsRoute
  '/election': typeof ElectionRoute
  '/endorsements': typeof EndorsementsRoute
  '/existing-members': typeof ExistingMembersRouteWithChildren
  '/finance': typeof FinanceRoute
  '/governance': typeof GovernanceRoute
  '/guests': typeof GuestsRoute
  '/login': typeof LoginRoute
  '/manage-committee': typeof ManageCommitteeRoute
  '/members': typeof MembersRouteWithChildren
  '/payment': typeof PaymentRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/register-member': typeof RegisterMemberRoute
  '/set-password': typeof SetPasswordRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/user-management': typeof UserManagementRouteWithChildren
  '/existing-members/$accountId': typeof ExistingMembersAccountIdRoute
  '/members/$applicationId': typeof MembersApplicationIdRoute
  '/user-management/$userAccountId': typeof UserManagementUserAccountIdRoute
  '/existing-members/': typeof ExistingMembersIndexRoute
  '/members/': typeof MembersIndexRoute
  '/user-management/': typeof UserManagementIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accommodation'
    | '/admin'
    | '/application'
    | '/applications'
    | '/committee-ballot'
    | '/documents'
    | '/election'
    | '/endorsements'
    | '/existing-members'
    | '/finance'
    | '/governance'
    | '/guests'
    | '/login'
    | '/manage-committee'
    | '/members'
    | '/payment'
    | '/profile'
    | '/register'
    | '/register-member'
    | '/set-password'
    | '/settings'
    | '/support'
    | '/user-management'
    | '/existing-members/$accountId'
    | '/members/$applicationId'
    | '/user-management/$userAccountId'
    | '/existing-members/'
    | '/members/'
    | '/user-management/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accommodation'
    | '/admin'
    | '/application'
    | '/applications'
    | '/committee-ballot'
    | '/documents'
    | '/election'
    | '/endorsements'
    | '/finance'
    | '/governance'
    | '/guests'
    | '/login'
    | '/manage-committee'
    | '/payment'
    | '/profile'
    | '/register'
    | '/register-member'
    | '/set-password'
    | '/settings'
    | '/support'
    | '/existing-members/$accountId'
    | '/members/$applicationId'
    | '/user-management/$userAccountId'
    | '/existing-members'
    | '/members'
    | '/user-management'
  id:
    | '__root__'
    | '/'
    | '/accommodation'
    | '/admin'
    | '/application'
    | '/applications'
    | '/committee-ballot'
    | '/documents'
    | '/election'
    | '/endorsements'
    | '/existing-members'
    | '/finance'
    | '/governance'
    | '/guests'
    | '/login'
    | '/manage-committee'
    | '/members'
    | '/payment'
    | '/profile'
    | '/register'
    | '/register-member'
    | '/set-password'
    | '/settings'
    | '/support'
    | '/user-management'
    | '/existing-members/$accountId'
    | '/members/$applicationId'
    | '/user-management/$userAccountId'
    | '/existing-members/'
    | '/members/'
    | '/user-management/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccommodationRoute: typeof AccommodationRoute
  AdminRoute: typeof AdminRoute
  ApplicationRoute: typeof ApplicationRoute
  ApplicationsRoute: typeof ApplicationsRoute
  CommitteeBallotRoute: typeof CommitteeBallotRoute
  DocumentsRoute: typeof DocumentsRoute
  ElectionRoute: typeof ElectionRoute
  EndorsementsRoute: typeof EndorsementsRoute
  ExistingMembersRoute: typeof ExistingMembersRouteWithChildren
  FinanceRoute: typeof FinanceRoute
  GovernanceRoute: typeof GovernanceRoute
  GuestsRoute: typeof GuestsRoute
  LoginRoute: typeof LoginRoute
  ManageCommitteeRoute: typeof ManageCommitteeRoute
  MembersRoute: typeof MembersRouteWithChildren
  PaymentRoute: typeof PaymentRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  RegisterMemberRoute: typeof RegisterMemberRoute
  SetPasswordRoute: typeof SetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SupportRoute: typeof SupportRoute
  UserManagementRoute: typeof UserManagementRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accommodation': {
      id: '/accommodation'
      path: '/accommodation'
      fullPath: '/accommodation'
      preLoaderRoute: typeof AccommodationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/application': {
      id: '/application'
      path: '/application'
      fullPath: '/application'
      preLoaderRoute: typeof ApplicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/committee-ballot': {
      id: '/committee-ballot'
      path: '/committee-ballot'
      fullPath: '/committee-ballot'
      preLoaderRoute: typeof CommitteeBallotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/election': {
      id: '/election'
      path: '/election'
      fullPath: '/election'
      preLoaderRoute: typeof ElectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/endorsements': {
      id: '/endorsements'
      path: '/endorsements'
      fullPath: '/endorsements'
      preLoaderRoute: typeof EndorsementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/existing-members': {
      id: '/existing-members'
      path: '/existing-members'
      fullPath: '/existing-members'
      preLoaderRoute: typeof ExistingMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance': {
      id: '/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof GovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guests': {
      id: '/guests'
      path: '/guests'
      fullPath: '/guests'
      preLoaderRoute: typeof GuestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage-committee': {
      id: '/manage-committee'
      path: '/manage-committee'
      fullPath: '/manage-committee'
      preLoaderRoute: typeof ManageCommitteeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-member': {
      id: '/register-member'
      path: '/register-member'
      fullPath: '/register-member'
      preLoaderRoute: typeof RegisterMemberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-management': {
      id: '/user-management'
      path: '/user-management'
      fullPath: '/user-management'
      preLoaderRoute: typeof UserManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/existing-members/': {
      id: '/existing-members/'
      path: '/'
      fullPath: '/existing-members/'
      preLoaderRoute: typeof ExistingMembersIndexRouteImport
      parentRoute: typeof ExistingMembersRoute
    }
    '/existing-members/$accountId': {
      id: '/existing-members/$accountId'
      path: '/$accountId'
      fullPath: '/existing-members/$accountId'
      preLoaderRoute: typeof ExistingMembersAccountIdRouteImport
      parentRoute: typeof ExistingMembersRoute
    }
    '/members/': {
      id: '/members/'
      path: '/'
      fullPath: '/members/'
      preLoaderRoute: typeof MembersIndexRouteImport
      parentRoute: typeof MembersRoute
    }
    '/members/$applicationId': {
      id: '/members/$applicationId'
      path: '/$applicationId'
      fullPath: '/members/$applicationId'
      preLoaderRoute: typeof MembersApplicationIdRouteImport
      parentRoute: typeof MembersRoute
    }
    '/user-management/': {
      id: '/user-management/'
      path: '/'
      fullPath: '/user-management/'
      preLoaderRoute: typeof UserManagementIndexRouteImport
      parentRoute: typeof UserManagementRoute
    }
    '/user-management/$userAccountId': {
      id: '/user-management/$userAccountId'
      path: '/$userAccountId'
      fullPath: '/user-management/$userAccountId'
      preLoaderRoute: typeof UserManagementUserAccountIdRouteImport
      parentRoute: typeof UserManagementRoute
    }
  }
}

interface ExistingMembersRouteChildren {
  ExistingMembersAccountIdRoute: typeof ExistingMembersAccountIdRoute
  ExistingMembersIndexRoute: typeof ExistingMembersIndexRoute
}

const ExistingMembersRouteChildren: ExistingMembersRouteChildren = {
  ExistingMembersAccountIdRoute: ExistingMembersAccountIdRoute,
  ExistingMembersIndexRoute: ExistingMembersIndexRoute,
}

const ExistingMembersRouteWithChildren = ExistingMembersRoute._addFileChildren(
  ExistingMembersRouteChildren,
)

interface MembersRouteChildren {
  MembersApplicationIdRoute: typeof MembersApplicationIdRoute
  MembersIndexRoute: typeof MembersIndexRoute
}

const MembersRouteChildren: MembersRouteChildren = {
  MembersApplicationIdRoute: MembersApplicationIdRoute,
  MembersIndexRoute: MembersIndexRoute,
}

const MembersRouteWithChildren =
  MembersRoute._addFileChildren(MembersRouteChildren)

interface UserManagementRouteChildren {
  UserManagementUserAccountIdRoute: typeof UserManagementUserAccountIdRoute
  UserManagementIndexRoute: typeof UserManagementIndexRoute
}

const UserManagementRouteChildren: UserManagementRouteChildren = {
  UserManagementUserAccountIdRoute: UserManagementUserAccountIdRoute,
  UserManagementIndexRoute: UserManagementIndexRoute,
}

const UserManagementRouteWithChildren = UserManagementRoute._addFileChildren(
  UserManagementRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccommodationRoute: AccommodationRoute,
  AdminRoute: AdminRoute,
  ApplicationRoute: ApplicationRoute,
  ApplicationsRoute: ApplicationsRoute,
  CommitteeBallotRoute: CommitteeBallotRoute,
  DocumentsRoute: DocumentsRoute,
  ElectionRoute: ElectionRoute,
  EndorsementsRoute: EndorsementsRoute,
  ExistingMembersRoute: ExistingMembersRouteWithChildren,
  FinanceRoute: FinanceRoute,
  GovernanceRoute: GovernanceRoute,
  GuestsRoute: GuestsRoute,
  LoginRoute: LoginRoute,
  ManageCommitteeRoute: ManageCommitteeRoute,
  MembersRoute: MembersRouteWithChildren,
  PaymentRoute: PaymentRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  RegisterMemberRoute: RegisterMemberRoute,
  SetPasswordRoute: SetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SupportRoute: SupportRoute,
  UserManagementRoute: UserManagementRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
